Rails.application.routes.draw do

  get 'contact' => 'contacts#show'

  root 'tracks#index'
  resource :track
  get 'tracking/:name/:id' => 'tracks#show'
  resource :dtdc
  get 'airstate' => 'airstates#show'
  get 'airwings' => 'airwingss#show'
  get 'akashganga' => 'akashgangas#show'
  get 'aramex' => 'aramexs#show'
  get 'blazeflash' => 'blazeflashs#show'
  get 'bluedart' => 'bluedarts#show'
  get 'bomgim' => 'bomgims#show'
  get 'bombino' => 'bombinos#show'
  get 'bondslogistics' => 'bondslogisticss#show'
  get 'cci' => 'ccis#show'
  get 'dhl' => 'dhls#show'
  get 'dotzot' => 'dotzots#show'
  get 'dpdindia' => 'dpdindias#show'
  get 'delhivery' => 'delhiverys#show'
  get 'eagle' => 'eagles#show'
  get 'ecomexpress' => 'ecomexpresss#show'
  get 'expressit' => 'expressits#show'
  get 'fedex' => 'fedexs#show'
  get 'firstflight' => 'firstflights#show'
  get 'flyking' => 'flykings#show'
  get 'gati' => 'gatis#show'
  get 'gmsexpress' => 'gmsexpresss#show'
  get 'corporate' => 'corporates#show'
  get 'gojavas' => 'gojavass#show'
  get 'madhur' => 'madhurs#show'
  get 'metromaruti' => 'metromarutis#show'
  get 'mirakle' => 'mirakles#show'
  get 'om' => 'oms#show'
  get 'omlogistic' => 'omlogisticss#show'
  get 'ondot' => 'ondots#show'
  get 'overnite' => 'overnites#show'
  get 'oxfordexpress' => 'oxfordexpresss#show'
  get 'pafex' => 'pafexs#show'
  get 'palande' => 'palandes#show'
  get 'indiaspeedpost' => 'indiaspeedposts#show'
  get 'pegasus' => 'pegasuss#show'
  get 'pigeonexpress' => 'pigeonexpresss#show'
  get 'poonam' => 'poonams#show'
  get 'professional' => 'professionals#show'
  get 'pushpak' => 'pushpaks#show'
  get 'quantium' => 'quantiums#show'
  get 'rapidconnect' => 'rapidconnects#show'
  get 'redexpress' => 'redexpresss#show'
  get 'safexpress' => 'safexpresss#show'
  get 'shreeanjani' => 'shreeanjanis#show'
  get 'shreemaruti' => 'shreemarutis#show'
  get 'shreetirupati' => 'shreetirupatis#show'
  get 'skynet' => 'skynets#show'
  get 'speedsafe' => 'speedsafes#show'
  get 'st' => 'sts#show'
  get 'tcixps' => 'tcixpss#show'
  get 'tnt' => 'tnts#show'
  get 'trackon' => 'trackons#show'
  get 'ubx' => 'ubxs#show'
  get 'united' => 'uniteds#show'
  get 'ups' => 'upss#show'
  get 'vrllogistics' => 'vrllogisticss#show'
  get 'xpressbees' => 'xpressbeess#show'
  #resources :cservices
end
